const fs = require("fs");

const urls = [
  "/weathers",
  "/pages/airline information",
  "/pages/flight information",
  "/v2/api/aodb/flight info",
  "/pages/transport parking",
  "/vayuvajras/stops",
  "/vayuvajras/services",
  "/vayuvajras/search",
  "/flybuses/stops",
  "/flybuses/search",
  "/pages/regulatory functions",
  "/pages/security",
  "/pages/e tourist visas",
  "/pages/experience",
  "/pages/culinary experience",
  "/pages/duty free store",
  "/pages/retail store",
  "/pages/quad by blr",
  "/pages/runway",
  "/pages/fire and ice",
  "/pages/bric a brac",
  "/pages/arena",
  "/pages/forex atms",
  "/pages/relax",
  "/pages/lounges",
  "/pages/taj by blr at bengaluru airport",
  "/pages/080 Transit Hotel",
  "/pages/estimatedWaitTime",
  "/pages/art and culture at blr airport",
  "/pages/butterfly artwork",
  "/pages/ashta mangala by siddhartha das",
  "/pages/lotus sutra by satish gupta",
  "/pages/the flight by yusuf arakkal",
  "/pages/protecting the heritage",
  "/pages/blr airport halt station",
  "/pages/self bag drop",
  "/pages/all services",
  "/pages/baggage wrapping",
  "/pages/baggage services",
  "/pages/all facilities",
  "/pages/wifi services",
  "/pages/baby care rooms",
  "/pages/smoking lounge",
  "/pages/local connectivity",
  "/pages/transit passenger",
  "/pages/buggy service",
  "/pages/special assistance services",
  "/pages/airport medical services",
  "/pages/multi faith room",
  "/pages/covid 19 test at bial",
  "/pages/meet assist",
  "/pages/lost found",
  "/lost and founds/search",
  "/lost and founds/claim",
  "/pages/about bial",
  "/pages/airline partners",
  "/pages/airport community app",
  "/pages/airport partners",
  "/pages/advertising",
  "/pages/cargo",
  "/pages/tenders",
  "/tender categories",
  "/tenders",
  "/tender/search",
  "/tenderdownload",
  "/tenders/bid",
  "/pages/reports and policies under bial",
  "/pages/on time performance report",
  "/pages/environmental clearance report",
  "/pages/newsroom",
  "/pages/news press releases",
  "/pages/image video gallery",
  "/pages/kempegowda international airport foundation",
  "/pages/careers",
  "/pages/faqs about blr airport bial",
  "/pages/disclaimer",
  "/pages/terms of use",
  "/pages/privacy policy",
  "/pages/copyright",
  "/pages/contact us",
  "/lost and founds/feedback",
  "/pages/press release",
  "/pages/feedback form",
  "/pages/our sustainability vision",
  "/pages/welcome to bial 1",
  "/pages/welcome to bial 2",
  "/pages/welcome to bial 3",
  "/pages/campaign",
  "/qms",
  "/pages/art and culture",
  "/pages/technology",
  "/pages/sustainability",
  "/pages/terminal in a garden",
  "/pages/covid 19 testing centre at blr airport",
  "/pages/lost and found luggage blr airport",
  "/pages/videos of bengaluru international airport",
  "/pages/action at blr airport",
  "/pages/voice of blr",
  "/flight info",
  "/pages/special needs",
  "/pages/passengers with reduced mobility",
  "/pages/terminal2",
  "/pages/wheelchair assistance",
  "/pages/sos",
  "/homepage/products",
  "/pages/map",
  "/pages/bial marketing 1",
  "/pages/press release aisats has been appointed by bial to develop a greenfield logistics",
  "/pages/press release blr airport s terminal   t  commences domestic operations",
  "/pages/press release blr airport named best airport by aci s asq arrival survey globally for the year     ",
  "/pages/press release blr airport rounds up cy      with impressive growth in passenger numbers and cargo volumes",
  "/pages/press release experience blr airport s terminal   in the metaverse ",
  "/pages/press release air india resumes its most popular bengaluru san francisco non stop ",
  "/pages/press release prime minister shri narendra modi inaugurates ",
  "/pages/press release blr airport records significant growth in passenger traffic in the current financial year",
  "/pages/press release airtel powers the swanky new terminal in kempegowda international airport ",
  "/pages/press release emirates a    debuts in bengaluru",
  "/pages/demo1",
  "/pages/demo2",
  "/pages/gallery",
  "/campaigns/campaign 1",
  "/homepages",
  "/pages/wti pickup directions",
  "/pages/transfers",
  "/pages/pulse nityotsava nallur tamarind grove",
  "/pages/pulse nityotsava bamboo grove",
  "/pages/pulse nityotsava ramnagara forest",
  "/pages/pulse v mana",
  "/pages/pulse garuda",
  "/pages/pulse bronze artifacts",
  "/pages/pulse a beautiful amalgamation",
  "/pages/pulse the journey of navarasa",
  "/pages/pulse tree of life and other works",
  "/pages/pulse astral body",
  "/pages/pulse impinged",
  "/pages/pulse sensorium of wonder",
  "/pages/pulse spiral of life",
  "/pages/pulse the symphony of emotions a visual exploration of expressions",
  "/pages/pulse khora",
  "/pages/pulse city of victory",
  "/pages/pulse nauraspur",
  "/pages/pulse structure",
  "/pages/pulse where we are coming from and where we going to",
  "/pages/pulse mirage",
  "/pages/pulse the moon",
  "/pages/pulse a case of wonder an ode to hampi",
  "/pages/pulse cactus",
  "/pages/pulse the tree of navarasa",
  "/pages/pulse heritage play celebrating traditional toys from karnataka",
  "/pages/pulse the soaring no3",
  "/pages/pulse burnt wood rockers",
  "/pages/pulse meghdoot",
  "/pages/pulse rani abbaka chowta",
  "/pages/pulse interpreted interpretations",
  "/pages/pulse still water troubled waters",
  "/pages/pulse that which encircles us",
  "/pages/pulse guess who i am",
  "/pages/pulse navarasa",
  "/pages/pulse trails of yakshagana",
  "/pages/pulse flights of wonder",
  "/pages/pulse find me a love song",
  "/pages/pulse earth formation",
  "/pages/pulse 12 sided pacchisi",
  "/pages/pulse 16 Sided Pacchisi",
  "/pages/pulse Anay kattu",
  "/pages/pulse Chauka bara",
  "/pages/pulse Four sided pacchisi",
  "/pages/pulse Four sided traditional pacchisi",
  "/pages/pulse Hasu chitaray",
  "/pages/pulse Knight’s magical tour",
  "/pages/pulse Six sided pacchisi",
  "/pages/pulse Vimana",
  "/pages/pulse four handed chaduranga",
  "/pages/pulse navagraha pagade",
  "/pages/pulse vivek mathew",
  "/pages/pulse ganesh shankar",
  "/pages/pulse dinesh maneer",
  "/pages/pulse tallur ln",
  "/pages/pulse madhu chandrika",
  "/pages/pulse tallur ln",
  "/pages/pulse sg vasudev",
  "/pages/pulse janarthanan rudhramoorthy",
  "/pages/pulse arunkumar hg",
  "/pages/pulse m a rauf",
  "/pages/pulse anupama hoskere",
  "/pages/pulse sanjay kumar",
  "/pages/pulse teja gavankar",
  "/pages/pulse mayadhara sahu",
  "/pages/pulse pragati mathur",
  "/pages/pulse saravanan parasuraman",
  "/pages/pulse ganesh selvaraj",
  "/pages/pulse harsha durugadda",
  "/pages/pulse krishnaraj chonat",
  "/pages/pulse sakshi gupta",
  "/pages/pulse suhasini kejriwal",
  "/pages/pulse alex davis",
  "/pages/pulse nagaraj bakale",
  "/pages/pulse cai zhisong",
  "/pages/pulse tarik currimbhoy",
  "/pages/pulse shanthamani muddaiah",
  "/pages/pulse foley design",
  "/pages/pulse namrata chhabria arjun",
  "/pages/pulse tanya mehta",
  "/pages/pulse pooja iranna",
  "/pages/pulse subodh kerkar",
  "/pages/pulse sarwesh shah",
  "/pages/pulse ravikumar kashi",
  "/pages/pulse shalini dam",
  "/pages/pulse latika katt",
  "/pages/pulse cosmos",
  "/pages/pulse santosh kumar chitragara",
  "/pages/pulse gaatha design studio",
  "/pages/pulse siddharth kaneria",
];

// Function to convert a URL to a question format
function urlToQuestion(url) {
  const parts = url.split("/").filter((part) => part !== ""); // Split the URL into parts and remove empty parts
  const lastPart = parts.pop(); // Get the last part of the URL

  // Convert the last part to a question format
  const question = `${lastPart.replace(/ /g, " ")}?`;

  return question;
}

// Create an array to store the questions
const questions = [];

// Loop through the URLs and convert them to questions
for (const url of urls) {
  const question = urlToQuestion(url);
  questions.push(question);
}

// Convert the questions array to JSON format
const jsonData = JSON.stringify(questions, null, 2);

// Write the JSON data to the output file
fs.writeFileSync("output.txt", jsonData, "utf8");

console.log("Questions saved to output.txt");
